### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Zpanther1** [ahmed5939/leach-bot#1]
Hey I am interested in making a leach bot but I would love some assistance. I downloaded the main files but am sort of confused what to do next.

**Comment by ahmed5939** [comment]
> Hey I am interested in making a leach bot but I would love some assistance. I downloaded the main files but am sort of confused what to do next.
hello there I can't really assist you unless I know what you're struggling with, so please describe what you're struggling with.

You can also join my Discord server and seek for help.

**Comment by ahmed5939** [comment]
> Hey I am interested in making a leach bot but I would love some assistance. I downloaded the main files but am sort of confused what to do next.


hello there I can't really assist you unless I know what you're struggling with, so please describe what you're struggling with.

You can also join my Discord server and seek for help.
